language: python
python:
  # - 2.7
  # - 3.2 not supported by pytest
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -r requirements/requirements-dev.txt && pip install -e .
script:
  - pytest tests/test_models.py
